docker: Error response from daemon: Conflict. The container name "/pg-docker" is already in use by container "5797dde0cd549531edb3910d30dde28692ee8a67001848643364e40f51199073". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
docker: Error response from daemon: Conflict. The container name "/pg-docker" is already in use by container "23815e72583ef6745c72b8b963c29313b37c5ee2612ca7c21c0a6d424157b91c". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2021-12-28 15:24:00.060 UTC [48] LOG:  starting PostgreSQL 13.5 (Debian 13.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2021-12-28 15:24:00.062 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-12-28 15:24:00.070 UTC [49] LOG:  database system was shut down at 2021-12-28 15:23:59 UTC
2021-12-28 15:24:00.076 UTC [48] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2021-12-28 15:24:00.318 UTC [48] LOG:  received fast shutdown request
waiting for server to shut down....2021-12-28 15:24:00.320 UTC [48] LOG:  aborting any active transactions
2021-12-28 15:24:00.323 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
2021-12-28 15:24:00.323 UTC [50] LOG:  shutting down
2021-12-28 15:24:00.340 UTC [48] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2021-12-28 15:24:00.450 UTC [1] LOG:  starting PostgreSQL 13.5 (Debian 13.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2021-12-28 15:24:00.450 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-12-28 15:24:00.450 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-12-28 15:24:00.454 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-12-28 15:24:00.460 UTC [62] LOG:  database system was shut down at 2021-12-28 15:24:00 UTC
2021-12-28 15:24:00.467 UTC [1] LOG:  database system is ready to accept connections
